//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Паркомат.
    /// </summary>
    [TrimmedStringStorage(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПаркоматE", new string[] {
            "НомерПарк as \'Номер паркомата\'"})]
    [View("ПаркоматL", new string[] {
            "НомерПарк as \'Номер паркомата\'"})]
    public class Паркомат : ICSSoft.STORMNET.DataObject
    {
        
        private string fАдрес;
        
        private int fНомерПарк;
        
        private IIS.Prilozhenie.Услуга fУслуга;
        
        private IIS.Prilozhenie.Парковка fПарковка;
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Паркомат.Адрес CustomAttributes)

        // *** End programmer edit section *** (Паркомат.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Паркомат.Адрес Get start)

                // *** End programmer edit section *** (Паркомат.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Паркомат.Адрес Get end)

                // *** End programmer edit section *** (Паркомат.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Паркомат.Адрес Set start)

                // *** End programmer edit section *** (Паркомат.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Паркомат.Адрес Set end)

                // *** End programmer edit section *** (Паркомат.Адрес Set end)
            }
        }
        
        /// <summary>
        /// НомерПарк.
        /// </summary>
        // *** Start programmer edit section *** (Паркомат.НомерПарк CustomAttributes)

        // *** End programmer edit section *** (Паркомат.НомерПарк CustomAttributes)
        public virtual int НомерПарк
        {
            get
            {
                // *** Start programmer edit section *** (Паркомат.НомерПарк Get start)

                // *** End programmer edit section *** (Паркомат.НомерПарк Get start)
                int result = this.fНомерПарк;
                // *** Start programmer edit section *** (Паркомат.НомерПарк Get end)

                // *** End programmer edit section *** (Паркомат.НомерПарк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Паркомат.НомерПарк Set start)

                // *** End programmer edit section *** (Паркомат.НомерПарк Set start)
                this.fНомерПарк = value;
                // *** Start programmer edit section *** (Паркомат.НомерПарк Set end)

                // *** End programmer edit section *** (Паркомат.НомерПарк Set end)
            }
        }
        
        /// <summary>
        /// Паркомат.
        /// </summary>
        // *** Start programmer edit section *** (Паркомат.Услуга CustomAttributes)

        // *** End programmer edit section *** (Паркомат.Услуга CustomAttributes)
        [PropertyStorage(new string[] {
                "Услуга"})]
        [NotNull()]
        public virtual IIS.Prilozhenie.Услуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (Паркомат.Услуга Get start)

                // *** End programmer edit section *** (Паркомат.Услуга Get start)
                IIS.Prilozhenie.Услуга result = this.fУслуга;
                // *** Start programmer edit section *** (Паркомат.Услуга Get end)

                // *** End programmer edit section *** (Паркомат.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Паркомат.Услуга Set start)

                // *** End programmer edit section *** (Паркомат.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (Паркомат.Услуга Set end)

                // *** End programmer edit section *** (Паркомат.Услуга Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Prilozhenie.Парковка.
        /// </summary>
        // *** Start programmer edit section *** (Паркомат.Парковка CustomAttributes)

        // *** End programmer edit section *** (Паркомат.Парковка CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Парковка"})]
        public virtual IIS.Prilozhenie.Парковка Парковка
        {
            get
            {
                // *** Start programmer edit section *** (Паркомат.Парковка Get start)

                // *** End programmer edit section *** (Паркомат.Парковка Get start)
                IIS.Prilozhenie.Парковка result = this.fПарковка;
                // *** Start programmer edit section *** (Паркомат.Парковка Get end)

                // *** End programmer edit section *** (Паркомат.Парковка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Паркомат.Парковка Set start)

                // *** End programmer edit section *** (Паркомат.Парковка Set start)
                this.fПарковка = value;
                // *** Start programmer edit section *** (Паркомат.Парковка Set end)

                // *** End programmer edit section *** (Паркомат.Парковка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПаркоматE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПаркоматE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПаркоматE", typeof(IIS.Prilozhenie.Паркомат));
                }
            }
            
            /// <summary>
            /// "ПаркоматL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПаркоматL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПаркоматL", typeof(IIS.Prilozhenie.Паркомат));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Паркомат.
    /// </summary>
    public class DetailArrayOfПаркомат : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Prilozhenie.DetailArrayOfПаркомат members)

        // *** End programmer edit section *** (IIS.Prilozhenie.DetailArrayOfПаркомат members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Паркомат by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Паркомат.
        /// </summary>
        public DetailArrayOfПаркомат(IIS.Prilozhenie.Парковка fПарковка) : 
                base(typeof(Паркомат), ((ICSSoft.STORMNET.DataObject)(fПарковка)))
        {
        }
        
        public IIS.Prilozhenie.Паркомат this[int index]
        {
            get
            {
                return ((IIS.Prilozhenie.Паркомат)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Prilozhenie.Паркомат dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
