//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Терминал.
    /// </summary>
    [TrimmedStringStorage(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТерминалE", new string[] {
            "НомерТер as \'Номер тер\'",
            "Адрес as \'Адрес\'"})]
    [View("ТерминалL", new string[] {
            "НомерТер as \'Номер тер\'",
            "Адрес as \'Адрес\'"})]
    public class Терминал : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерТер;
        
        private string fАдрес;
        
        private IIS.Prilozhenie.Парковка fПарковка;
        
        /// <summary>
        /// Адрес.
        /// </summary>
        // *** Start programmer edit section *** (Терминал.Адрес CustomAttributes)

        // *** End programmer edit section *** (Терминал.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                // *** Start programmer edit section *** (Терминал.Адрес Get start)

                // *** End programmer edit section *** (Терминал.Адрес Get start)
                string result = this.fАдрес;
                // *** Start programmer edit section *** (Терминал.Адрес Get end)

                // *** End programmer edit section *** (Терминал.Адрес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Терминал.Адрес Set start)

                // *** End programmer edit section *** (Терминал.Адрес Set start)
                this.fАдрес = value;
                // *** Start programmer edit section *** (Терминал.Адрес Set end)

                // *** End programmer edit section *** (Терминал.Адрес Set end)
            }
        }
        
        /// <summary>
        /// НомерТер.
        /// </summary>
        // *** Start programmer edit section *** (Терминал.НомерТер CustomAttributes)

        // *** End programmer edit section *** (Терминал.НомерТер CustomAttributes)
        public virtual int НомерТер
        {
            get
            {
                // *** Start programmer edit section *** (Терминал.НомерТер Get start)

                // *** End programmer edit section *** (Терминал.НомерТер Get start)
                int result = this.fНомерТер;
                // *** Start programmer edit section *** (Терминал.НомерТер Get end)

                // *** End programmer edit section *** (Терминал.НомерТер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Терминал.НомерТер Set start)

                // *** End programmer edit section *** (Терминал.НомерТер Set start)
                this.fНомерТер = value;
                // *** Start programmer edit section *** (Терминал.НомерТер Set end)

                // *** End programmer edit section *** (Терминал.НомерТер Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Prilozhenie.Парковка.
        /// </summary>
        // *** Start programmer edit section *** (Терминал.Парковка CustomAttributes)

        // *** End programmer edit section *** (Терминал.Парковка CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Парковка"})]
        public virtual IIS.Prilozhenie.Парковка Парковка
        {
            get
            {
                // *** Start programmer edit section *** (Терминал.Парковка Get start)

                // *** End programmer edit section *** (Терминал.Парковка Get start)
                IIS.Prilozhenie.Парковка result = this.fПарковка;
                // *** Start programmer edit section *** (Терминал.Парковка Get end)

                // *** End programmer edit section *** (Терминал.Парковка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Терминал.Парковка Set start)

                // *** End programmer edit section *** (Терминал.Парковка Set start)
                this.fПарковка = value;
                // *** Start programmer edit section *** (Терминал.Парковка Set end)

                // *** End programmer edit section *** (Терминал.Парковка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТерминалE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТерминалE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТерминалE", typeof(IIS.Prilozhenie.Терминал));
                }
            }
            
            /// <summary>
            /// "ТерминалL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТерминалL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТерминалL", typeof(IIS.Prilozhenie.Терминал));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Терминал.
    /// </summary>
    public class DetailArrayOfТерминал : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Prilozhenie.DetailArrayOfТерминал members)

        // *** End programmer edit section *** (IIS.Prilozhenie.DetailArrayOfТерминал members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Терминал by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Терминал.
        /// </summary>
        public DetailArrayOfТерминал(IIS.Prilozhenie.Парковка fПарковка) : 
                base(typeof(Терминал), ((ICSSoft.STORMNET.DataObject)(fПарковка)))
        {
        }
        
        public IIS.Prilozhenie.Терминал this[int index]
        {
            get
            {
                return ((IIS.Prilozhenie.Терминал)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Prilozhenie.Терминал dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
