//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Услуги.
    /// </summary>
    // *** Start programmer edit section *** (Услуги CustomAttributes)

    // *** End programmer edit section *** (Услуги CustomAttributes)
    public enum Услуги
    {
        
        // *** Start programmer edit section *** (Услуги.1 CustomAttributes)

        // *** End programmer edit section *** (Услуги.1 CustomAttributes)
        [Caption("15 минут")]
        1,
        
        // *** Start programmer edit section *** (Услуги.2 CustomAttributes)

        // *** End programmer edit section *** (Услуги.2 CustomAttributes)
        [Caption("от 15 до 60 минут")]
        2,
        
        // *** Start programmer edit section *** (Услуги.3 CustomAttributes)

        // *** End programmer edit section *** (Услуги.3 CustomAttributes)
        [Caption("свыше 60 минут")]
        3,
    }
}
